import express from "express";
import router from "./Routes/mainRoutes.js"; 
import cors from 'cors';
import dotenv from 'dotenv';
import mongose from './dbConnection/db.js';
import cookieParser from "cookie-parser";
import cloudRouter from "./Routes/uploadRoutes.js";
import profileRouter from "./Routes/profileRoutes.js";
dotenv.config();
const app = express();
app.use(cookieParser());
app.use(cors({origin: `${process.env.URL}`, // Frontend URL
    credentials: true}));
app.use(express.json());
mongose();
app.use('/app',router);
app.use('/upload',cloudRouter);
app.use('/profile',profileRouter);
let PORT = process.env.PORT;
app.listen(PORT,()=>{console.log(`Server is running on ${PORT}`)});